version: '3.7'

services:
# Start messaging broker
  master-rabbitmq:
    image: rabbitmq:3.6.5-management
    hostname: "master-rabbitmq"
    deploy: 
      mode: global
      placement:
        constraints:
          - node.hostname == heel
    dns: ["8.8.8.8"]
    ports:
      - "5672:5672"
      - "15672:15672" #Management Server
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"
      #RABBITMQ_DISK_FREE_LIMIT: "1GB"
  slave-rabbitmq:
    image: rabbitmq:3.6.5-management
    hostname: "slave-rabbitmq"
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == leg
    dns: ["8.8.8.8"]
    links:
      - "master-rabbitmq:master-rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"
  # Start transformation worker
  strokewidthtransform:
    image: thanhtung3512/open-ocr-preprocessor
    volumes:
      - /var/ocr/docker-compose/scripts/:/opt/ocr/
    dns: ["8.8.8.8"]
    networks:
      - overlay
    depends_on:
      - master-rabbitmq
    command: "/opt/ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@master-rabbitmq/ -preprocessor stroke-width-transform"

  # Start OCR worker
  openocrworker:
    image: thanhtung3512/${OPEN_OCR_INSTANCE}
    deploy:
      replicas: 5
    volumes:
      - /var/ocr/docker-compose/scripts/:/opt/ocr/
    dns: ["8.8.8.8"]
    depends_on:
      - master-rabbitmq
    command: "/opt/ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@master-rabbitmq/"
    environment: 
      GOOGLE_APPLICATION_CREDENTIALS: "/opt/ocr/apivision.json"

  # Start http server
  openocr:
    image: thanhtung3512/${OPEN_OCR_INSTANCE}
    deploy:
      replicas: 5
    volumes:
      - /var/ocr/docker-compose/scripts/:/opt/ocr/
    ports:
      - "8888:8888"
    dns: ["8.8.8.8"]
    depends_on:
      - master-rabbitmq
      - openocrworker
      - strokewidthtransform
    command: "/opt/ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@master-rabbitmq/ -http_port 8888"
